package com.divoom.Divoom.bluetooth;

public class SppProc
{
  public static enum CMD_TYPE
  {
    private int _value;
    
    static
    {
      SPP_CHANGE_MODE = new CMD_TYPE("SPP_CHANGE_MODE", 1, 5);
      SPP_GET_SD_MUSIC_LIST = new CMD_TYPE("SPP_GET_SD_MUSIC_LIST", 2, 7);
      SPP_SET_SD_PLAY_MUSIC_ID = new CMD_TYPE("SPP_SET_SD_PLAY_MUSIC_ID", 3, 17);
      SPP_SET_LAST_NEXT = new CMD_TYPE("SPP_SET_LAST_NEXT", 4, 18);
      SPP_SEND_SD_LIST_OVER = new CMD_TYPE("SPP_SEND_SD_LIST_OVER", 5, 20);
      SPP_SEND_SD_TF_STATUS = new CMD_TYPE("SPP_SEND_SD_TF_STATUS", 6, 21);
      SPP_GET_SD_MUSIC_LIST_TOTAL_NUM = new CMD_TYPE("SPP_GET_SD_MUSIC_LIST_TOTAL_NUM", 7, 125);
      SPP_GET_SD_MUSIC_INFO = new CMD_TYPE("SPP_GET_SD_MUSIC_INFO", 8, 180);
      SPP_SET_SD_MUSIC_POSITION = new CMD_TYPE("SPP_SET_SD_MUSIC_POSITION", 9, 184);
      SPP_SET_SD_MUSIC_PLAY_MODE = new CMD_TYPE("SPP_SET_SD_MUSIC_PLAY_MODE", 10, 185);
      SPP_SET_VOL = new CMD_TYPE("SPP_SET_VOL", 11, 8);
      SPP_GET_VOL = new CMD_TYPE("SPP_GET_VOL", 12, 9);
      SPP_SET_PLAY_STATUS = new CMD_TYPE("SPP_SET_PLAY_STATUS", 13, 10);
      SPP_GET_PLAY_STATUS = new CMD_TYPE("SPP_GET_PLAY_STATUS", 14, 11);
      SPP_GET_STDB_MODE = new CMD_TYPE("SPP_GET_STDB_MODE", 15, 19);
      SPP_SET_SYSTEM_TIME = new CMD_TYPE("SPP_SET_SYSTEM_TIME", 16, 24);
      SPP_SET_TEMP_TYPE = new CMD_TYPE("SPP_SET_TEMP_TYPE", 17, 43);
      SPP_SET_HPUR_TYPE = new CMD_TYPE("SPP_SET_HPUR_TYPE", 18, 45);
      SPP_LIGHT_CURRENT_LEVEL = new CMD_TYPE("SPP_LIGHT_CURRENT_LEVEL", 19, 49);
      SPP_LIGHT_ADJUST_LEVEL = new CMD_TYPE("SPP_LIGHT_ADJUST_LEVEL", 20, 50);
      SPP_SAND_PAINT_CTRL = new CMD_TYPE("SPP_SAND_PAINT_CTRL", 21, 52);
      SPP_SCROLL = new CMD_TYPE("SPP_SCROLL", 22, 53);
      SPP_DRAWING_MUL_PAD_CTRL = new CMD_TYPE("SPP_DRAWING_MUL_PAD_CTRL", 23, 58);
      SPP_SET_ANCS_NOTICE_PIC = new CMD_TYPE("SPP_SET_ANCS_NOTICE_PIC", 24, 60);
      SPP_MOVE_RESET_IFRAME = new CMD_TYPE("SPP_MOVE_RESET_IFRAME", 25, 62);
      SPP_SET_SLEEP_TIME = new CMD_TYPE("SPP_SET_SLEEP_TIME", 26, 64);
      SPP_SET_SLEEP_SCENE = new CMD_TYPE("SPP_SET_SLEEP_SCENE", 27, 65);
      SPP_GET_ALARM_TIME_SCENE = new CMD_TYPE("SPP_GET_ALARM_TIME_SCENE", 28, 66);
      SPP_SET_ALARM_TIME_SCENE = new CMD_TYPE("SPP_SET_ALARM_TIME_SCENE", 29, 67);
      SPP_SET_BOX_MODE = new CMD_TYPE("SPP_SET_BOX_MODE", 30, 69);
      SPP_GET_BOX_MODE = new CMD_TYPE("SPP_GET_BOX_MODE", 31, 70);
      SPP_SET_BOX_COLOR = new CMD_TYPE("SPP_SET_BOX_COLOR", 32, 68);
      SPP_APP_NEED_GET_MUSIC_LIST = new CMD_TYPE("SPP_APP_NEED_GET_MUSIC_LIST", 33, 71);
      SPP_SET_MUL_BOX_COLOR = new CMD_TYPE("SPP_SET_MUL_BOX_COLOR", 34, 73);
      SPP_SET_ANDROID_ANCS = new CMD_TYPE("SPP_SET_ANDROID_ANCS", 35, 80);
      SPP_SET_ALARM_TIME_GIF = new CMD_TYPE("SPP_SET_ALARM_TIME_GIF", 36, 81);
      SPP_SET_BOOT_GIF = new CMD_TYPE("SPP_SET_BOOT_GIF", 37, 82);
      SPP_GET_DIALY_TIME_EXT2 = new CMD_TYPE("SPP_GET_DIALY_TIME_EXT2", 38, 83);
      SPP_SET_DIALY_TIME_EXT2 = new CMD_TYPE("SPP_SET_DIALY_TIME_EXT2", 39, 84);
      SPP_SET_DIALY_TIME_GIF = new CMD_TYPE("SPP_SET_DIALY_TIME_GIF", 40, 85);
      SPP_SET_TIME_MANAGE_INFO = new CMD_TYPE("SPP_SET_TIME_MANAGE_INFO", 41, 86);
      SPP_GET_TIME_MANAGE_CTRL = new CMD_TYPE("SPP_GET_TIME_MANAGE_CTRL", 42, 87);
      SPP_DRAWING_PAD_CTRL = new CMD_TYPE("SPP_DRAWING_PAD_CTRL", 43, 88);
      SPP_DRAWING_PAD_EXIT = new CMD_TYPE("SPP_DRAWING_PAD_EXIT", 44, 90);
      SPP_DRAWING_ENCODE_PIC = new CMD_TYPE("SPP_DRAWING_ENCODE_PIC", 45, 91);
      SPP_DRAWING_ENCODE_PLAY = new CMD_TYPE("SPP_DRAWING_ENCODE_PLAY", 46, 92);
      SPP_SEND_NET_TEMP_INFO = new CMD_TYPE("SPP_SEND_NET_TEMP_INFO", 47, 93);
      SPP_SEND_NET_TEMP_DISP_INFO = new CMD_TYPE("SPP_SEND_NET_TEMP_DISP_INFO", 48, 94);
      SPP_SEND_CUR_NET_TEMP = new CMD_TYPE("SPP_SEND_CUR_NET_TEMP", 49, 95);
      SPP_GET_DEVICE_TEMP_INFO = new CMD_TYPE("SPP_GET_DEVICE_TEMP_INFO", 50, 89);
      SPP_SET_MIX_MUISE_MODE = new CMD_TYPE("SPP_SET_MIX_MUISE_MODE", 51, 106);
      SPP_SET_NEW_MIX_MUSIC_MODE = new CMD_TYPE("SPP_SET_NEW_MIX_MUSIC_MODE", 52, 188);
      SPP_GET_FM_CURRENT_FREQ = new CMD_TYPE("SPP_GET_FM_CURRENT_FREQ", 53, 96);
      SPP_SET_FM_CURRENT_FREQ = new CMD_TYPE("SPP_SET_FM_CURRENT_FREQ", 54, 97);
      SPP_SET_FM_AUTOMATIC_SEARCH = new CMD_TYPE("SPP_SET_FM_AUTOMATIC_SEARCH", 55, 99);
      SPP_GET_FM_COUNT_OR_FREQ = new CMD_TYPE("SPP_GET_FM_COUNT_OR_FREQ", 56, 100);
      SPP_SET_FM_FAVOURITE = new CMD_TYPE("SPP_SET_FM_FAVOURITE", 57, 103);
      SPP_GET_FM_AUTOMATIC_SEARCH_STATUS = new CMD_TYPE("SPP_GET_FM_AUTOMATIC_SEARCH_STATUS", 58, 104);
      SPP_DRAWING_MUL_ENCODE_GIF_PLAY = new CMD_TYPE("SPP_DRAWING_MUL_ENCODE_GIF_PLAY", 59, 107);
      SPP_DRAWING_MUL_PAD_ENTER = new CMD_TYPE("SPP_DRAWING_MUL_PAD_ENTER", 60, 111);
      SPP_DRAWING_ENCODE_MOVIE_PLAY = new CMD_TYPE("SPP_DRAWING_ENCODE_MOVIE_PLAY", 61, 108);
      SPP_DRAWING_MUL_ENCODE_MOVIE_PLAY = new CMD_TYPE("SPP_DRAWING_MUL_ENCODE_MOVIE_PLAY", 62, 109);
      SPP_DRAWING_CTRL_MOVIE_PLAY = new CMD_TYPE("SPP_DRAWING_CTRL_MOVIE_PLAY", 63, 110);
      SPP_SET_FM_REGION = new CMD_TYPE("SPP_SET_FM_REGION", 64, 105);
      SPP_GET_FM_REGION = new CMD_TYPE("SPP_GET_FM_REGION", 65, 112);
      SPP_GET_TOOL_INFO = new CMD_TYPE("SPP_GET_TOOL_INFO", 66, 113);
      SPP_SET_TOOL_INFO = new CMD_TYPE("SPP_SET_TOOL_INFO", 67, 114);
      SPP_GET_NET_TEMP_DISP_INFO = new CMD_TYPE("SPP_GET_NET_TEMP_DISP_INFO", 68, 115);
      SPP_SET_SYSTEM_BRIGHT = new CMD_TYPE("SPP_SET_SYSTEM_BRIGHT", 69, 116);
      SPP_SET_DEVICE_NAME = new CMD_TYPE("SPP_SET_DEVICE_NAME", 70, 117);
      SPP_SET_MUL_DEVICE_CTRL = new CMD_TYPE("SPP_SET_MUL_DEVICE_CTRL", 71, 119);
      SPP_LED_UPDATE_FONT_INFO = new CMD_TYPE("SPP_LED_UPDATE_FONT_INFO", 72, 124);
      SPP_SET_DIVOOM_LEAVE_MSG_GIF = new CMD_TYPE("SPP_SET_DIVOOM_LEAVE_MSG_GIF", 73, 126);
      SPP_SET_ALARM_VOICE_CTRL = new CMD_TYPE("SPP_SET_ALARM_VOICE_CTRL", 74, 130);
      SPP_SET_SONG_DIS_CTRL = new CMD_TYPE("SPP_SET_SONG_DIS_CTRL", 75, 131);
      SPP_RESET_NOTIFICATIONS = new CMD_TYPE("SPP_RESET_NOTIFICATIONS", 76, 132);
      SPP_SEND_HOTCTRL = new CMD_TYPE("SPP_SEND_HOTCTRL", 77, 133);
      SPP_SEND_LED_WORD_CMD = new CMD_TYPE("SPP_SEND_LED_WORD_CMD", 78, 134);
      SPP_SEND_GAME_SHARK = new CMD_TYPE("SPP_SEND_GAME_SHARK", 79, 136);
      SPP_GET_FILE_VERSION = new CMD_TYPE("SPP_GET_FILE_VERSION", 80, 151);
      SPP_APP_UPDATE_FILE_INFO = new CMD_TYPE("SPP_APP_UPDATE_FILE_INFO", 81, 152);
      SPP_APP_SEND_FILE_DATA = new CMD_TYPE("SPP_APP_SEND_FILE_DATA", 82, 153);
      SPP_PAUSE_SYS_UPDATE_DATA = new CMD_TYPE("SPP_PAUSE_SYS_UPDATE_DATA", 83, 72);
      SPP_SEND_HOT_FILE_LIST = new CMD_TYPE("SPP_SEND_HOT_FILE_LIST", 84, 155);
      SPP_REQUEST_FILE_INFO = new CMD_TYPE("SPP_REQUEST_FILE_INFO", 85, 156);
      SPP_HOT_UPDATE_FILE_INFO = new CMD_TYPE("SPP_HOT_UPDATE_FILE_INFO", 86, 157);
      SPP_HOT_SEND_FILE_DATA = new CMD_TYPE("SPP_HOT_SEND_FILE_DATA", 87, 158);
      SPP_HOT_PAUSE_FILE_SEND = new CMD_TYPE("SPP_HOT_PAUSE_FILE_SEND", 88, 159);
      SPP_SYS_DEVICE_UPDATE = new CMD_TYPE("SPP_SYS_DEVICE_UPDATE", 89, 147);
      SPP_SYS_UPDATE_DATA = new CMD_TYPE("SPP_SYS_UPDATE_DATA", 90, 148);
      SPP_SYS_CONTINUE_UPDATE_DATA = new CMD_TYPE("SPP_SYS_CONTINUE_UPDATE_DATA", 91, 149);
      SPP_SYS_GET_UPDATE_ADDR = new CMD_TYPE("SPP_SYS_GET_UPDATE_ADDR", 92, 150);
      SPP_SET_GAME = new CMD_TYPE("SPP_SET_GAME", 93, 160);
      SPP_SET_TALK = new CMD_TYPE("SPP_SET_TALK", 94, 161);
      SPP_GET_SCENE = new CMD_TYPE("SPP_GET_SCENE", 95, 162);
      SPP_SET_SCENE_LISTEN = new CMD_TYPE("SPP_SET_SCENE_LISTEN", 96, 163);
      SPP_SET_SCENE_LISTEN_VOLUME = new CMD_TYPE("SPP_SET_SCENE_LISTEN_VOLUME", 97, 164);
      SPP_SET_ALARM_LISTEN = new CMD_TYPE("SPP_SET_ALARM_LISTEN", 98, 165);
      SPP_SET_ALARM_LISTEN_VOLUME = new CMD_TYPE("SPP_SET_ALARM_LISTEN_VOLUME", 99, 166);
      SPP_SET_SOUND_CTRL = new CMD_TYPE("SPP_SET_SOUND_CTRL", 100, 167);
      SPP_GET_SOUND_CTRL = new CMD_TYPE("SPP_GET_SOUND_CTRL", 101, 168);
      SPP_SET_PLAY_STOP_VOICE = new CMD_TYPE("SPP_SET_PLAY_STOP_VOICE", 102, 169);
      SPP_GET_PLAY_VOICE_STATUS = new CMD_TYPE("SPP_GET_PLAY_VOICE_STATUS", 103, 170);
      SPP_SET_AUTO_POWER_OFF = new CMD_TYPE("SPP_SET_AUTO_POWER_OFF", 104, 171);
      SPP_GET_AUTO_POWER_OFF = new CMD_TYPE("SPP_GET_AUTO_POWER_OFF", 105, 172);
      SPP_SET_SLEEP_COLOR = new CMD_TYPE("SPP_SET_SLEEP_COLOR", 106, 173);
      SPP_SET_SLEEP_LIGHT = new CMD_TYPE("SPP_SET_SLEEP_LIGHT", 107, 174);
      SPP_SET_CONNECTED_FLAG = new CMD_TYPE("SPP_SET_CONNECTED_FLAG", 108, 175);
      SPP_GET_CONNECTED_FLAG = new CMD_TYPE("SPP_GET_CONNECTED_FLAG", 109, 176);
      SPP_SET_USER_GIF = new CMD_TYPE("SPP_SET_USER_GIF", 110, 177);
      SPP_SET_ENERGY_CTRL = new CMD_TYPE("SPP_SET_ENERGY_CTRL", 111, 178);
      SPP_GET_ENERGY_CTRL = new CMD_TYPE("SPP_GET_ENERGY_CTRL", 112, 179);
      SPP_MODIFY_RHYTHM_ITEMS = new CMD_TYPE("SPP_MODIFY_RHYTHM_ITEMS", 113, 182);
      SPP_SET_RHYTHM_GIF = new CMD_TYPE("SPP_SET_RHYTHM_GIF", 114, 183);
    }
    
    private CMD_TYPE(int paramInt)
    {
      this._value = paramInt;
    }
    
    public int value()
    {
      return this._value;
    }
  }
  
  public static enum LIGHT_MODE
  {
    private byte[] cmd_data;
    
    static
    {
      COLOR_LIGHT = new LIGHT_MODE("COLOR_LIGHT", 2, new byte[] { 2 });
      SPECIAL_LIGHT = new LIGHT_MODE("SPECIAL_LIGHT", 3, new byte[] { 3 });
    }
    
    private LIGHT_MODE(byte[] paramArrayOfByte)
    {
      this.cmd_data = paramArrayOfByte;
    }
    
    public byte[] getCmd_data()
    {
      return this.cmd_data;
    }
  }
  
  public static enum WORK_MODE
  {
    private byte _value;
    
    private WORK_MODE(byte paramByte)
    {
      this._value = paramByte;
    }
    
    public byte value()
    {
      return this._value;
    }
  }
}
